[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.135.1",
    "uvicorn==0.41.0",
    "sqlalchemy==2.0.48",
    "alembic==1.18.4",
    "psycopg2-binary==2.9.11",
    "pydantic-settings==2.13.1",
    "python-dotenv==1.2.2",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff==0.15.7", # Movido aquí
]

[tool.ruff]
src = ["app"]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# E: Errores de estilo (estilo Black)
# W: warnings de estilo
# F: Errores de lógica (Pyflakes)
# I: Orden de imports (isort)
# B: Prevención de bugs comunes (flake8-bugbear)
# UP: Sugerencias de sintaxis moderna (pyupgrade)
# ARG: Argumentos inutilizados (flake8)
# T20: Printeos en produccion
select = ["E", "W","F", "I", "B", "UP", "ARG", "T20"]
ignore = [
    "E501",
    "B008",
]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.setuptools]
# Esto le dice a pip qué carpetas incluir como paquetes

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
